enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('enquete/<int:pk>', views.DetalhesView.as_view(), name = 'detalhes'),
    path('enquete/<int:pk>/results', views.ResultadoView.as_view(), name = 'results'),
    path('enquete/<int:id_enquete>/votacao', views.votacao, name = 'votacao'),
    path('enquete/<int:pk>/comment_detalhe', views.comment_detalhe, name = 'comment_detalhe')
]

main/models.py
from django.db import models
from django.utils import timezone
import datetime

class Pergunta(models.Model):
    texto = models.CharField(max_length = 200)
    data_publicacao = models.DateTimeField('Data de Publicação')
    def __str__(self):
        return self.texto

    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora


class Opcao(models.Model):
    texto = models.CharField(max_length = 200)
    votos = models.IntegerField(default = 0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

class Comment(models.Model):
    autor = models.CharField(max_length= 50)
    texto = models.TextField()
    data = models.DateTimeField(auto_now_add=True)
    pergunta = models.ForeignKey(Pergunta, related_name= "comments" ,on_delete=models.CASCADE)

main/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Pergunta, Opcao, Comment

class IndexView(generic.ListView):
    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()
        ).order_by('-data_publicacao')[:5]


class DetalhesView(generic.DetailView):
    model = Pergunta
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())


class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/results.html'

def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'main/details.html', {
            'pergunta': pergunta,
            'error_message': "Selecione uma opção VÁLIDA!"
        })
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(
            reverse('main:results', args=(pergunta.id,))
        )
def comment_detalhe(req, pk):
    comment = get_object_or_404(Comment, pk=pk)
    return render(req, 'main/comment_detalhe.html', {'comment':comment})

main/templates/main/comment_detalhe.html
<h2>{{ comment.autor }}</h2> 
{{ comment.texto }}
<h3>Publicado em: {{ comment.data }}</h3>


<a href="{% url 'main:detalhes' comment.pergunta.id %}">Voltar para enquete</a><br />
<a href="/">Voltar para home</a>

main/templates/main/pergunta_detail.html
<!DOCTYPE html>
<html>
<head>
	<title>Details</title>
</head>
<body>

	<h2>Detalhes da Enquete {{ pergunta.id }}</h2>
        <u>Pergunta</u>: {{ pergunta.texto }}<br/>
        <u>Data de Publicação</u>: {{ pergunta.data_publicacao }}
        {% if error_message %}
            <hr/>
            <strong>{{ error_message }}</strong>
            <hr/>
        {% endif %}
        <form action="{% url 'main:votacao' pergunta.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li><input type="radio" name="opcao"
                        id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
                        <label for="opcao{{ forloop.counter }}">
                            {{ opcao.texto }}
                        </label>
                    </li>
                {% endfor %}
            </ul>
            <input type="submit" value="Registre o seu Voto">
        </form>
        <h2>Comentários</h2>
        {% if not pergunta.comments.all %}
            Sem comentários ainda
        {% endif %}
        {% for comment in pergunta.comments.all %}
            <a href="{% url 'main:comment_detalhe' comment.id %}"> {{ comment.texto }} </a><br />
        {% endfor %}
        <hr>
        <a href="{% url 'main:index' %}">Retorne a página principal</a>

</body>
</html>

main/templates/main/pergunta_list.html
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>
	{% if pergunta_list %}
        <h2>Lista das Últimas Enquetes</h2>
        <ul>
            {% for pergunta in pergunta_list %}
                <li><a href="{% url 'main:detalhes' pergunta.id %}">
                    {{ pergunta.texto }}
                </a> (<a href="{% url 'main:results' pergunta.id %}">ver parcial</a>)</li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Não há enquetes cadastradas até o momento!</h3>
    {% endif %}

</body>
</html>

main/templates/main/results.html
<!DOCTYPE html>
<html>
<head>
	<title>Results</title>
</head>
<body>
	<h2>Resultado Parcial da Enquete {{ pergunta.id }}</h2>
    <u>Pergunta</u>: {{ pergunta.texto }}<br/>
    <u>Data de Publicação</u>: {{ pergunta.data_publicacao }}
    <ul>
        {% for opcao in pergunta.opcao_set.all %}
            <li>{{ opcao.texto }} = {{ opcao.votos }}
            voto{{ opcao.votos | pluralize }}</li>
        {% endfor %}
    </ul>
    <hr/>
    <a href="{% url 'main:detalhes' pergunta.id %}">Deseja votar novamente?</a> |
    <a href="{% url 'main:index' %}">Retornar à página principal</a>

</body>
</html>